#!/bin/env bash

if [[ "$1" == "clean" ]]; then
	cd ./src
	make clean
	exit 0
fi

if [ $(id -u) -ne 0 ]; then
	echo "Please run as root."
	exit 1
fi

cp -f ./config.def.h ./src/config.def.h
cd ./src
./install_main
