#!/usr/bin/env bash

if [ -f ./config.h ]; then
    echo "config.h should not exist."
    echo "config.h is generated by config.def.h"
    exit 1
fi

echo "==> copying config.h"
echo
cp -fv config.def.h config.h
echo

echo "==> compiling..."
echo
make
echo
echo "==> installing..."
echo
sudo make install
echo

if [ ! -f /usr/share/licenses/dwm/LICENSE ]; then
    echo "LICENSE file not installed. Installing..."
    sudo install -m644 -D LICENSE "/usr/share/licenses/dwm/LICENSE"
    echo
fi

if [ ! -f /usr/share/doc/dwm/README.md ]; then
    echo "README.md not installed. Installing..."
    sudo install -m644 -D README.md "/usr/share/doc/dwm/README.md"
    echo
fi

if [ ! -f  /usr/share/xsessions/dwm.desktop ]; then
    echo "dwm.desktop not installed. Installing..."
    sudo install -m644 -D ./dwm.desktop "/usr/share/xsessions/dwm.desktop"
    echo
fi

echo "==> removing config.h"
echo
rm -v ./config.h
echo
echo "==> build finished."
