#!/bin/bash

function command_exists() {
	command -v "$1" &> /dev/null 2>&1
}

if ! command_exists xidlehook ; then
	echo 'xidlehook not installed'
	exit 1
fi
if ! command_exists light ; then
	echo 'light not installed'
	exit 1
fi

function run() {
	xidlehook \
		`# Don't lock when there's a fullscreen application` \
		--not-when-fullscreen \
		`# Don't lock when there's audio playing` \
		--not-when-audio \
		`# Dim the screen after 3 minutes, undim if user becomes active` \
		--timer $1 \
		'echo "$(light | cut -d'.' -f1)" > /tmp/_TMP_LIGHT_VAL; if [ $(light | cut -d'.' -f1) -ge 15 ]; then light -S 15; fi'\
		'if [ -f /tmp/_TMP_LIGHT_VAL ]; then light -S $(cat /tmp/_TMP_LIGHT_VAL); else light -S 100; fi' \
		`# Undim & lock after 15 more minutes` \
		--timer $2 \
		'~/scripts/lock; sleep 2.5; if [ -f /tmp/_TMP_LIGHT_VAL ]; then light -S $(cat /tmp/_TMP_LIGHT_VAL); else light -S 100; fi' \
		'' \
		`# Finally, suspend half an hour after it locks` \
		--timer $3 \
		'systemctl suspend' \
		''
}

if [[ "$1" == "-d" ]]; then
	run 10 10 10
else
	run 180 900 1800
fi
