#!/bin/env bash
DEFAULT_SINK=$(pactl get-default-sink)
VOL_PERC=$(pactl get-sink-volume $DEFAULT_SINK | cut -d'/' -f2 | xargs | cut -d' ' -f1)
VOL_STAT=$(pactl get-sink-mute $DEFAULT_SINK | cut -d' ' -f2)
VOL_PERC_INT=${VOL_PERC:0:-1}

ID=0
if [[ $VOL_STAT == "yes" ]]; then
    ID=3
else
    if [ $VOL_PERC_INT -ge 0 ] && [ $VOL_PERC_INT -le 20 ]; then
        ID=2
    elif [ $VOL_PERC_INT -le 60 ]; then
        ID=1
    else
        ID=0
    fi
fi

ICONS=("🔊" "🔉" "🔈" "🔇")
ICON=${ICONS[$ID]}
MSG=""
if [[ $VOL_STAT == "no" ]]; then
    MSG="$VOL_PERC"
elif [[ $VOL_STAT == "yes" ]]; then
    MSG="muted"
else
    MSG="$VOL_STAT"
fi

echo "$ICON $MSG"
