#!/bin/bash
# rm -f /tmp/screenshot*.png /tmp/screenlock.png
# scrot /tmp/screenshot.png
# convert /tmp/screenshot.png -blur 0x20 /tmp/screenshotblur.png
# convert /tmp/screenshotblur.png ~/scripts/banner_resize.png -gravity center -composite -matte /tmp/screenlock.png

i3lock-fancy -t "FrozenArcher -- HJJ" &
